
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 06 04:44:38 CDT 2023
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 11;
  public static final int coma = 10;
  public static final int comillas = 12;
  public static final int EOF = 0;
  public static final int ll_cierre = 3;
  public static final int P_coma = 6;
  public static final int Identificador = 5;
  public static final int error = 1;
  public static final int charac = 7;
  public static final int inte = 4;
  public static final int mas = 9;
  public static final int igual = 8;
  public static final int ll_apertura = 2;
}

